In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [2]:
holidays=pd.read_csv('holidays_events.csv')
oil=pd.read_csv('oil.csv')
stores=pd.read_csv('stores.csv')
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
sample=pd.read_csv('sample_submission.csv')
transactions=pd.read_csv('transactions.csv')

Holidays_events Cleaning

In [6]:
holidays.head()
holidays.info()
holidays.isnull().sum()
holidays['date']=pd.to_datetime(holidays['date'])

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    str
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), str(5)
memory usage: 14.1 KB

In [14]:
holidays.duplicated().sum()

np.int64(0)

In [ ]:
holidays.to_csv('holidays_events done.csv',index=False)

Oil Clean

In [17]:
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [20]:
oil.info()
oil['date']=pd.to_datetime(oil['date'])
oil.shape

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[us]
 1   dcoilwtico  1175 non-null   float64
dtypes: datetime64[us](1), float64(1)
memory usage: 19.2 KB

(1218, 2)

In [21]:
oil.isnull().sum()

date           0
dcoilwtico    43
dtype: int64

In [23]:
oil.dropna(inplace=True)

In [24]:
oil.to_csv('oil done.csv',index=False)

Sample_Submission

In [25]:
sample.head()

        id  sales
0  3000888    0.0
1  3000889    0.0
2  3000890    0.0
3  3000891    0.0
4  3000892    0.0

In [26]:
sample.duplicated().sum()

np.int64(0)

In [30]:
sample.dtypes
sample['id']=sample['id'].astype(str)
sample.to_csv('sample_submission done.csv',index=False)

In [35]:
stores.head()
stores.info()
stores.isnull().sum()
stores.duplicated().sum()
stores.to_csv('stores done.csv',index=False)

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     str
 2   state      54 non-null     str
 3   type       54 non-null     str
 4   cluster    54 non-null     int64
dtypes: int64(2), str(3)
memory usage: 2.2 KB

In [39]:
test.head()
test.info()
test['id']=test['id'].astype(str)
test['date']=pd.to_datetime(test['date'])

<class 'pandas.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  str
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  str
 4   onpromotion  28512 non-null  int64
dtypes: int64(3), str(2)
memory usage: 1.1 MB

In [43]:
test.info()
test.isnull().sum()
test.duplicated().sum()
test.to_csv('test done.csv',index=False)

<class 'pandas.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  str
 1   date         28512 non-null  datetime64[us]
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  str
 4   onpromotion  28512 non-null  int64
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 1.1 MB

In [50]:
train.head()
train.info()
train['date']=pd.to_datetime(train['date'])
train['id']=train['id'].astype(str)
train.info()
train.isnull().sum()
train.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           str
 1   date         datetime64[us]
 2   store_nbr    int64
 3   family       str
 4   sales        float64
 5   onpromotion  int64
dtypes: datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 137.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           str
 1   date         datetime64[us]
 2   store_nbr    int64
 3   family       str
 4   sales        float64
 5   onpromotion  int64
dtypes: datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 137.4 MB

np.int64(0)

In [51]:
train.to_csv('train done.csv',index=False)

In [54]:
transactions.head()
transactions.info()
transactions['date']=pd.to_datetime(transactions['date'])
transactions.isnull().sum() 
transactions.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.9 MB

np.int64(0)

In [57]:
transactions.isnull().sum() 
transactions.to_csv('transactions done.csv',index=False)